### ISSUE TITLE
Error in odkfw_input_channel.cpp

### ISSUE THREAD

**Issue by andrescass** [DEWETRON/OXYGEN-SDK#1]
In line 31 of odkfw_input_channel.cpp says:
`return getChannelId() != std::numeric_limits<uint64>::max();`

it shlould say uint64_t

**Comment by mponiz** [comment]
Thank you for bringing this issue to our attention.
We just pushed the code using the correct datatype.

**Comment by andrescass** [comment]
Great. I close the issue
