### ISSUE TITLE
QI INSTALL

### ISSUE THREAD

**Issue by BrunoDEWETRONSERVICES** [DEWETRON/OXYGEN-SDK#18]
Hi,
In the Quickstart RST Files, the version of QT is not specify.
The open source version is it OK to use or it's necessary to use commercial version ?

**Comment by matthiasstraka** [comment]
Hi,
the open source version of QT is sufficient, our current build runs fine with 5.15.X versions in Windows or 5.12.X for Ubuntu 20.04.
It is possible to build on Windows using the supplied qt ressource bundle (https://github.com/DEWETRON/OXYGEN-SDK/releases/tag/OXYGEN-SDK-R6.1.0)
