### ISSUE TITLE
Problems with CMAKE Install

### ISSUE THREAD

**Issue by BrunoDEWETRONSERVICES** [DEWETRON/OXYGEN-SDK#19]
Hi

I have some problems to configure CMAKE.
In the PDF file, it's writing "(for example C:\\Qt\\5.15.2\\msvc2017_64)* but i have (for example C:\\Qt\\5.15.2\\msvc2019_64)*
Is it a problem to work correctly ?

![Erreur CMAKE](https://user-images.githubusercontent.com/111748649/186180438-8e141852-9fb2-4901-9514-b301da92de20.PNG)
![ODK Intsall with Python](https://user-images.githubusercontent.com/111748649/186180443-b5c790e4-6c0f-4e38-b6a6-5c03dc624abe.PNG)
![Erreur CMAKE 2](https://user-images.githubusercontent.com/111748649/186180446-73db9d7e-ec18-4877-acc4-dd25c44dbbde.PNG)
Could you help me pls ?
Just an idea : 
In view of the difficulties in setting up my environment to develop, do you have a Virtual Machine already preconfigured to dowmnload (VMWARE, VIRTALBOX for example).
Thanks

**Comment by matthiasstraka** [comment]
Unfortunately, we do not offer a virtual machine. I assume you successfully executed the `setup.py` file. You do not really need a full installation of QT. Downloading our bundle [qt_resource_compiler.zip](https://github.com/DEWETRON/OXYGEN-SDK/releases/download/OXYGEN-SDK-6.0.0/qt_resource_compiler.zip) and extracting it in your `C:\OXYGEN-SDK` directory is sufficient (`setup.py` should have done that already). There is no need to set  `QT_DIR` in this case.

It now looks like you only are missing a minor detail: two dots so cmake knows that your sources are in the parent directory of `build`.

In the documentation you will find the cmake call as
```C:\OXYGEN-SDK\build> cmake -A x64 ..```
Usually, you can omit the `-A x64` and just call `cmake ..` from the `build` directory.

I just verified the steps with the latest version and I did not run into any problems following the  guide. Let me know if you now can build the files on your machine.
