### ISSUE TITLE
Oxygen don't load custom plugins

### ISSUE THREAD

**Issue by andrescass** [DEWETRON/OXYGEN-SDK#2]
I am following the wiki build instructions. I've downloaded the SDK and boost library. Cmake and open the solution in Visual Studio.
I've compiled the examples without compiling errors and also I've created a new project and compiled it.
Then I've copied the .plugin files to {PublicDocuments}\Dewetron\Oxygen\Plugins and to C:\Program Files\DEWETRON\Oxygen\bin, but when I open Oxygen, plugins don't appear in settings-overview nor in the add channel window.

If I erase the plgin files that came with installation (like ethernet or matlab_export) they dissapear of the setting-overview when I open again Oxygen, and reappear if I copy them again to bin folder. But that is not happening with my own plugins.

I've tried with all the build configurations and with copying them to bin folder, to public documents folder, and both. And nothing works

**Comment by mponiz** [comment]
We have just checked the code of your plugin and discovered a small mishap in the UUID of your plugin:
The 3rd group of the UUID "42R2" includes a non-hexadecimal digit ('R')
After changing this to something valid and recompiling the plugin seems to load fine, and the channel is addable.

Please let us know, if this helped to solve your issue.
Best Regards

**Comment by andrescass** [comment]
I've corrected the UUID (and pushed changes to my repo) but it's still not loading in Oxygen.
I'm using Oxygen for developers 5.0.2. I've tried in a WIndows 7 and in a WIndows 10 PC and it's the same.
I think I must be missing some step. 
I compile the plugin in Visual Studio 2017 using release configurtation (I've also tried Degbug configuration) from the project-compile option of VIsual Studio. Then I copy .plugin file to Program Files/Dewetron/Oxygen/bin directory, as said in the wiki.
Is there anything else I have to do? Any configuration?
I've also tried with the examples included in the SDK.

Thank you very much for the response

**Comment by mponiz** [comment]
We have tried to reproduce you issue locally at our site, but so far without success.

Could you please provide the Oxygen.log - file, after you deployed the plugin to "Program Files/Dewetron/Oxygen/bin" and have started Oxygen once?
The log-file is located in {PublicDocuments}\Dewetron\Oxygen\Log

If you could also provide one of the self-built plugins as a binary file that might help to understand the issue at hand.

Thank you and Best Regards

**Comment by andrescass** [comment]
Thank you for trying. Attached goes the log file and one of the examples. 
I want to describe every step I've maked in order to see if I am missing something.

Environment: Desktop PC with Windows 7 / Laptop with WIndows 10 (both presents the same problem)
Visual Studio Community 2017
Oxygen for devs 5.0.2 downloaded from https://ccc.dewetron.com/Productlines/view/564af6b0-7628-4d66-b2f7-2d6bd9c49861#sdkversion
SDK downloaded from this repository.
boost 1.70.0
CMake 3.18.0-rc2

I followed the wiki procedure:
- I've downloaded the boost library and copied it to the 3rd party folder into the SDK.
- Created the build folder and run 'cmake ..' from inside it.
- Opened odk.sln in Visual Studio 2017.
- Opened one of the examples (or my own project) and compile it with Project->compile in Visual Studio. I've tryied with Release and Debug configuration, always using Win32 as target.
- Copied the .plugin file to C:\Program Files\Dewetron\Oxygen\bin
- Launch Oxygen

Recently a plugin was sent to me, and I try it and works. So I think I must be doing something wrong at compile/build the plugin.

Looking into the log file, I can see that in both plugins made by me, there is an error legend that says "%1 no es una aplicación Win32 válida." In english it is "%1 is not a valid Win32 application". I think that is the problem, but I don't know how to fix it.

Thank you

[Oxygen.log](https://github.com/DEWETRON/OXYGEN-SDK/files/4871218/Oxygen.log)
[ex_bin_detector.zip](https://github.com/DEWETRON/OXYGEN-SDK/files/4871222/ex_bin_detector.zip)

**Comment by glaure** [comment]
Hello!

You are building the plugins for the x86 (32bit) architecture. As Oxygen is a x64 (amd_x64, 64bit) application, you have to choose **x64** as build target for the plugin.

Best regards
Gunther

**Comment by andrescass** [comment]
I thought on this first, but I've found so much errors when I tried to compile to x64 that I discard it.
Now, I've got through the projecto configurations and, after a couple of hours fighting with Visual Studio, I could get it to work.
Trank you for the responses. Issue closed
