### ISSUE TITLE
Function SetMasterTimeStamp

### ISSUE THREAD

**Issue by arnaudDewetronfrance** [DEWETRON/OXYGEN-SDK#22]
Dear , 

We are working on a plugin for automotive bus decoding. 

We are using the function getmastertimestamp to correlate the data to the tick but as no channel is activated , timebase of 10000000 is defined by default. 

No function SetMasterTimeStamp has been identified to define it freely. 

Do you have a way to resolve it ? 

Best regards

**Comment by mfauster** [comment]
The master timebase frequency is determined internally by Oxygen based on the measurement setup. To ensure the highest precision it is usually based on a daq hardware clock and therefore cannot be changed freely.

You need to use a timebase conversion function to map timestamps from their frequency to the expected resolution.
