### ISSUE TITLE
How to Debug a Plugin

### ISSUE THREAD

**Issue by HpLightcorner** [DEWETRON/OXYGEN-SDK#3]
Hey Dewetron Team,
I am developing a custom plugin and so far everything works perfectly (also due to your well down wiki).

Without working through your plugin-loading way, is there a simple and efficient way to debug a plugin? (and I mean true debugging inside Visual Studio - of course I am already using log files)...

If so, It would be great to add some documentation.
Kind regards

**Comment by glaure** [comment]
One way is to start Oxygen using Visual Studio.

![grafik](https://user-images.githubusercontent.com/11034654/86563918-932ca480-bf65-11ea-9c2c-cb497112b061.png)

Or you can attach to a running Oxygen process:

![grafik](https://user-images.githubusercontent.com/11034654/86564086-dbe45d80-bf65-11ea-9cec-5a303d4495fa.png)

Then you can set breakpoints in your plugins source code.

Best regards
Gunt

**Comment by HpLightcorner** [comment]
Hey,
I will immediately give it a try - and let you know if everything works as expected.

**Comment by HpLightcorner** [comment]
Works perfectly -thanks in advance!
