### ISSUE TITLE
Adding a new property

### ISSUE THREAD

**Issue by ravivelugula** [DEWETRON/OXYGEN-SDK#43]
Hi 

I am facing an issue while adding a new property in the plugin code. Initially one property (resistance) is added, and the plugin worked fine. However as I am adding one more property (flux constant) along with resistance, the plugin not generated as the code  showing some issues. I adding the code in the "code" section of GitHub.

Kindly help in the regard. Thanks in advance

Ravi
PhD
IIT Madras

**Comment by ravivelugula** [comment]
Hi,

Upon doing the definition of computeOutput() with two arguments, the plugin created and worked properly. However, I am unable enter the decimal or float values in the oxygen while entering the corresponding property values. 
![image](https://github.com/user-attachments/assets/4d5ca9d8-4af9-4672-b6af-24b47a4b7944)

can you suggest possible solution for the same?

**Comment by glaure** [comment]
You are adding these properties with:
```
        , m_resi_ance(std::make_shared<EditableUnsignedProperty>(0.9, 0.1, 10))
        , m_flux_cons(std::make_shared<EditableUnsignedProperty>(0.066, 0.001, 10))
```

By using EditableUnsignedProperty you are defining the property to be a positive integral type.

```
    std::shared_ptr<EditableFloatingPointProperty> m_resi_ance;
    std::shared_ptr<EditableFloatingPointProperty> m_flux_cons;
```
    
and

```
        , m_resi_ance(std::make_shared<EditableFloatingPointProperty>(0.9, 0.1, 10))
        , m_flux_cons(std::make_shared<EditableFloatingPointProperty>(0.066, 0.001, 10))
```
in the constructor.

Bye Gunther

**Comment by ravivelugula** [comment]
Hi,

Thanks for solution. It working fine and giving correct output with some minor changes (like replacing in to double). 
![image](https://github.com/user-attachments/assets/5564ce8d-696c-496c-95bf-d5c08b77f848)
